INFO:__main__:Fitting model at time: 2021-09-09 09:13:23.805070
Traceback (most recent call last):
  File "train_model.py", line 171, in <module>
    model, train_loss, test_loss = train_model(
  File "train_model.py", line 113, in train_model
    out = model(batch.to(DEVICE))
  File "/zhome/2b/7/117471/Thesis/venv-thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/2b/7/117471/Thesis/src/models/models.py", line 458, in forward
    x = self.conv1_sh(x=x, edge_index=edge_index)  # , edge_weight=edge_weight)
  File "/zhome/2b/7/117471/Thesis/venv-thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/2b/7/117471/Thesis/venv-thesis/lib/python3.8/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 154, in forward
    out = self.propagate(edge_index, x=(x_l, x_r), size=size)
  File "/zhome/2b/7/117471/Thesis/venv-thesis/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 237, in propagate
    out = self.message(**msg_kwargs)
  File "/zhome/2b/7/117471/Thesis/venv-thesis/lib/python3.8/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 179, in message
    x = x_i + x_j
RuntimeError: CUDA out of memory. Tried to allocate 222.00 MiB (GPU 0; 15.78 GiB total capacity; 13.74 GiB already allocated; 171.50 MiB free; 14.29 GiB reserved in total by PyTorch)
